module projetcorba {
  module election {

	interface processus {
		attribute long uid;
        	attribute string successeur; //uid du successeur du processus en question
		attribute string successeurPanne; //uid du successeur de successeur du processus en question
		void recevoir(inout long max);
		
	};

  };

};
